### ISSUE TITLE
Trouble understanding the (short) FastQ output

### ISSUE THREAD

**Issue by ConradStack** [gmiclotte/Jabba#4]
I can successfully run your software, but I am having trouble understanding the format of the short FastQ files that it outputs.  As I understand it, Jabba splits a PacBio read in to multiple subreads, concatenating _1, _2, _3, ... to the original long read name.  But each of the FastQ entries for these subreads seem to contain the original quality score, which is much longer than the any of the individual sequences.  When I try reading these data (e.g., with bioawk, Geneious) they all crash or return errors.  

I ended up converting the short FastQ file to FastA using `sed`:

`sed -e '/^+$/ { N; d;}' -e 's/^@/>/' short.fastq > short.fasta`

Could you help me understand why the output files look like this?  And whether or not the quality scores of the corrected reads are still valuable?

**Comment by gmiclotte** [comment]
Hello, the maintained version of Jabba was moved to [the biointec github page](https://github.com/biointec/jabba). There you can find the most recent version, which will always output to fasta format, since the algorithm that Jabba uses does not allow us to keep track of the quality scores.

I'll edit the readme here to make this move clear, my apologies for the inconvenience.

**Comment by ConradStack** [comment]
Thanks!
